Repository android-password-store/Android-Password-Store, pull requests merged in 2020-06, with the labels that each got.

#841 Allow custom public suffixes for Autofill
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/PublicSuffixListCache.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: :gift: feature

#840 Remove Apache Commons dependencies
  app/build.gradle
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/FileUtils.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  dependencies.gradle
Labels: 🔨 code

#844 Dependency updates
  app/build.gradle
  app/proguard-rules.pro
  dependencies.gradle
Labels: 📚 dependencies

#776 Break down PGP Activity into focused sections
  CHANGELOG.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/ClipboardService.kt
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/SelectFolderActivity.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillPreferenceActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/BasePgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/GetKeyIdsActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/PasswordGeneratorDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/XkPasswordGeneratorDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/ClipboardUtils.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordItem.kt
  app/src/main/java/mozilla/components/lib/publicsuffixlist/ext/ByteArray.kt
  app/src/main/res/layout/decrypt_layout.xml
  app/src/main/res/layout/password_creation_activity.xml
  app/src/main/res/menu/context_pass.xml
  app/src/main/res/menu/pgp_handler_new_password.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: :sos: help wanted, 🔨 code

#850 UserPreference: delete all shortcuts when repository is deleted
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
Labels: 🐛 bug

#855 Improve bulk deletion and password move flow
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🐛 bug, 🔨 code

#860 Refactor password generation
  app/src/main/java/com/zeapo/pwdstore/pwgen/PasswordGenerator.kt
  app/src/main/java/com/zeapo/pwdstore/pwgen/Phonemes.kt
  app/src/main/java/com/zeapo/pwdstore/pwgen/RandomNumberGenerator.kt
  app/src/main/java/com/zeapo/pwdstore/pwgen/RandomPasswordGenerator.kt
  app/src/main/java/com/zeapo/pwdstore/pwgen/RandomPhonemesGenerator.kt
  app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/PasswordBuilder.kt
  app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/XkpwdDictionary.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/PasswordGeneratorDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/XkPasswordGeneratorDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/res/values/strings.xml
Labels: 🔨 code

#854 Add support for category renaming
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
  app/src/main/res/layout/folder_dialog_fragment.xml
  app/src/main/res/menu/context_pass.xml
  app/src/main/res/values/strings.xml
Labels: :gift: feature

#862 PasswordStore: refresh password list on swipe down in non-git mode
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
Labels: 🐛 bug

#863 UserPreference: fix my inability to count
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
Labels: 🐛 bug

#867 PasswordCreationActivity: properly guard rename code
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
Labels: :black_circle: regression, 🐛 bug

#871 Add org.gnu.icecat as a trusted multi-origin browser
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FeatureAndTrustDetection.kt
Labels: browser-support

#873 Replace YAML with HTML in F-Droid fastlane summary
  fastlane/metadata/android/en-US/full_description.txt
Labels: :scroll: documentation, 🐛 bug

#874 Add paragraphs to F-Droid summary
  fastlane/metadata/android/en-US/full_description.txt
Labels: :scroll: documentation

#876 Remove Android Arsenal badge
  README.md
Labels: :scroll: documentation

#877 Add Google Play/F-Droid badges to the README
  README.md
Labels: :scroll: documentation

#882 build: uprev all dependencies
  app/proguard-rules.pro
  dependencies.gradle
Labels: 📚 dependencies

#885 Reset SSH passphrase after SSH key import
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
Labels: backport, bug

#880 Use remembered credential even if it is empty
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
Labels: backport, regression

#892 UI fixups
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
  app/src/main/res/layout/password_row_layout.xml
Labels: ready

#887 Consolidate password list refresh
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/git/BreakOutOfDetached.kt
  app/src/main/java/com/zeapo/pwdstore/git/CloneOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.kt
  app/src/main/java/com/zeapo/pwdstore/git/PullOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/PushOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/ResetToRemoteOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
Labels: To investigate

#893 Rework GitHub Actions
  .github/workflows/branch_deploy.yml
  .github/workflows/draft_new_release.yml
Labels: backport

#890 Reintroduce TOTP support
  CHANGELOG.md
  app/build.gradle
  app/src/androidTest/java/com/zeapo/pwdstore/utils/UriTotpFinderTest.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/BasePgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Otp.kt
  app/src/main/java/com/zeapo/pwdstore/utils/TotpFinder.kt
  app/src/main/java/com/zeapo/pwdstore/utils/UriTotpFinder.kt
  app/src/main/res/layout/decrypt_layout.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/zeapo/pwdstore/PasswordEntryTest.kt
  app/src/test/java/com/zeapo/pwdstore/model/PasswordEntryTest.kt
  app/src/test/java/com/zeapo/pwdstore/utils/OtpTest.kt
  dependencies.gradle
Labels: backport, documentation, feature, in progress

#897 Merge SshKeyGenFragment into its activity
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
  app/src/main/res/layout/activity_ssh_keygen.xml
Labels: code, ready

#899 Offer TOTP Autofill for OTP fields
  CHANGELOG.md
  app/build.gradle
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillScenario.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategy.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategyDsl.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/OreoAutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt
  dependencies.gradle
Labels: feature, ready

#898 Workaround to prevent crash on first run
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
Labels: backport, bug, discussion, in progress

#903 Allow importing TOTP configuration through QR codes
  CHANGELOG.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/res/drawable/ic_qr_code_scanner.xml
  app/src/main/res/layout/password_creation_activity.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: feature, ready

#904 Revert "Support directly importing secrets"
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
Labels: ready

#891 Use PreferenceKeys file to manage SharedPreferences keys.
  app/src/main/java/com/zeapo/pwdstore/Application.kt
  app/src/main/java/com/zeapo/pwdstore/ClipboardService.kt
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/PublicSuffixListCache.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/BasePgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/GetKeyIdsActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/SshApiSessionFactory.java
  app/src/main/java/com/zeapo/pwdstore/pwgen/PasswordGenerator.kt
  app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/XkpwdDictionary.kt
  app/src/main/java/com/zeapo/pwdstore/ui/adapters/PasswordItemRecyclerAdapter.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/PasswordGeneratorDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
Labels: code
