Repository android-password-store/Android-Password-Store, pull requests merged in 2020-10, with the labels that each got.

#1129 Allow matching password fields based on hints only
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FormField.kt
Labels: feature

#1136 Fix Autofill publisher changed layout
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillPublisherChangedActivity.kt
  app/src/main/res/layout/activity_oreo_autofill_publisher_changed.xml
Labels: bug

#1139 build: update runtime dependencies and Gradle plugins
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: dependencies

#1134 Introduce app-wide HTTPS proxy setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/Application.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/GitSettings.kt
  app/src/main/java/com/zeapo/pwdstore/ui/proxy/ProxySelectorActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/AndroidExtensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/java/com/zeapo/pwdstore/utils/ProxyUtils.kt
  app/src/main/res/layout/activity_proxy_selector.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: feature

#1148 ProxyUtils: correctly handle the 'no proxy' case
  app/src/main/java/com/zeapo/pwdstore/utils/ProxyUtils.kt
Labels: blocking-release, bug

#1153 Backmerge release branch
  CHANGELOG.md
  app/build.gradle.kts
Labels: merge-strategy: fast-forward

#1137 Add option to automatically sync repository on app launch
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/layout/activity_launch.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: feature

#1156 Revamp build configuration
  .github/workflows/deploy_snapshot.yml
  .github/workflows/release.yml
  .gitignore
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/res/layout/oreo_autofill_dataset.xml
  app/src/main/res/layout/oreo_autofill_filter_row.xml
  autofill-parser/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/buildDependencies.gradle
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/BinaryCompatibilityValidator.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/KotlinCompilerArgs.kt
  buildSrc/src/main/java/PasswordStorePlugin.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  scripts/deploy-snapshot.sh
  scripts/encrypt-secret.sh
  scripts/signing-cleanup.sh
  scripts/signing-setup.sh
  secrets/keystore.cipher
  secrets/props.cipher
Labels: dependencies, merge-strategy: fast-forward

#1159 Fix auth mode switching and expand URL validation
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug

#1162 Remove accessibility autofill support
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillFragment.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillPreferenceActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillRecyclerAdapter.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/drawable-nodpi/autofill_ins_1.webp
  app/src/main/res/drawable-nodpi/autofill_ins_2.webp
  app/src/main/res/drawable-nodpi/autofill_ins_3.webp
  app/src/main/res/layout/autofill_instructions.xml
  app/src/main/res/layout/autofill_recycler_view.xml
  app/src/main/res/layout/autofill_row_layout.xml
  app/src/main/res/layout/fragment_autofill.xml
  app/src/main/res/menu/autofill_preference.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-v26/bools.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/bools.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/autofill_config.xml
  app/src/main/res/xml/preference.xml
Labels: type: feature-deprecation

#1165 Rollback automatic synchronization feature
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/layout/activity_launch.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: type: bug, type: feature-deprecation

#1169 Update GitHub Actions workflows
  .github/workflows/deploy_snapshot.yml
  .github/workflows/draft_new_release.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .github/workflows/update_publicsuffix_data.yml
  .github/workflows/validate_wrapper.yml
Labels: merge-strategy: fast-forward

#1168 Workaround AndroidX lifecycle requirements in OpenKeychain auth
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/BreakOutOfDetached.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/CloneOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/PullOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/PushOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/ResetToRemoteOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/ContinuationContainerActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/OpenKeychainKeyProvider.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshjSessionFactory.kt
Labels: type: bug

#1170 Minimal support for MIME secret encoding
  app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt
  app/src/test/java/com/zeapo/pwdstore/model/PasswordEntryTest.kt
Labels: type: feature

#1176 github: add workflow to track dependency tree changes
  .github/workflows/dependency-tree-diff.yml
Labels: area: ci/cd

#1177 Update kotlinx.coroutines and WhatTheStack
  .github/workflows/dependency-tree-diff.yml
  buildSrc/src/main/java/Dependencies.kt
Labels: area: dependencies

#1179 Finish activity when Autofill Generate is cancelled
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
Labels: type: bug
