Repository android-password-store/Android-Password-Store, pull requests merged in 2020-09, with the labels that each got.

#1070 Add Keystore backend for SSH public key authentication
  CHANGELOG.md
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/zeapo/pwdstore/Application.kt
  app/src/main/java/com/zeapo/pwdstore/ClipboardService.kt
  app/src/main/java/com/zeapo/pwdstore/Migrations.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/git/ErrorMessages.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/OpenKeychainKeyProvider.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshKey.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshjConfig.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshjSessionFactory.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/ShowSshKeyFragment.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/BiometricAuthenticator.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/layout/activity_ssh_keygen.xml
  app/src/main/res/layout/folder_dialog_fragment.xml
  app/src/main/res/layout/fragment_show_ssh_key.xml
  app/src/main/res/layout/git_credential_layout.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: documentation, feature

#1072 github: update workflows to use peter-evans/create-pull-request
  .github/workflows/draft_new_release.yml
  .github/workflows/update_publicsuffix_data.yml
Labels: ready

#1066 Refactor Git operations and auth
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitOperationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/BreakOutOfDetached.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/CloneOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/PullOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/PushOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/ResetToRemoteOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Result.kt
  app/src/main/res/layout/activity_git_clone.xml
  app/src/main/res/menu/git_clone.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: code

#1075 Remove BaseGitActivity's onOptionsItemSelected override
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
Labels: bug

#1068 Revamp onboarding logic
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/OnboardingActivity.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, code, help wanted, in progress

#1076 Add migration to new SshKey backend
  app/src/main/java/com/zeapo/pwdstore/Migrations.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshKey.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
Labels: bug

#1077 Assorted UX improvements
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/OnboardingActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/CredentialFinder.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
Labels: bug

#1080 DecryptActivity: properly calculate remaining OTP time on first pass
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
Labels: bug

#1081 PasswordRepository: add custom FS factory for symlink capabilities
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
Labels: bug

#1082 Update dependencies and add EditorConfig file
  .editorconfig
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: code, dependencies

#1083 Fix changelog links
  .github/workflows/draft_new_release.yml
  CHANGELOG.md
Labels: code

#1088 Use same checks as BiometricAuthenticator in UserPreference
  .editorconfig
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/utils/BiometricAuthenticator.kt
Labels: bug

#825 Support multiple authentication methods
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/OpenKeychainKeyProvider.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshjSessionFactory.kt
Labels: feature

#1090 Fix directory selection in onboarding if storage permissions are granted
  app/src/main/java/com/zeapo/pwdstore/OnboardingActivity.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
Labels: bug, code

#1091 Autofill: add kiwi as a supported browser
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FeatureAndTrustDetection.kt
  app/src/main/res/xml/oreo_autofill_service.xml
Labels: browser-support

#1094 build: update Kotlin and dependency-updates plugin
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: dependencies

#1093 Disable SSH multiplexing if not supported
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/GitSettings.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/PullOperation.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
Labels: bug

#1095 Correctly count children in password list
  app/src/main/java/com/zeapo/pwdstore/ui/adapters/PasswordItemRecyclerAdapter.kt
Labels: bug

#1097 Continue onboarding if permissions are granted prematurely
  app/src/main/java/com/zeapo/pwdstore/OnboardingActivity.kt
Labels: bug

#1098 PasswordRepository: properly gate symlink feature
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
Labels: bug

#1100 Add tentative workaround for dialog crashes and refactor Git-related code
  app/src/main/java/com/zeapo/pwdstore/OnboardingActivity.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
Labels: bug

#1099 Update on-boarding UI
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/ui/onboarding/activity/OnboardingActivity.kt
  app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/CloneFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/RepoLocationFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/WelcomeFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/FragmentExtensions.kt
  app/src/main/res/animator/slide_in_left.xml
  app/src/main/res/animator/slide_in_right.xml
  app/src/main/res/animator/slide_out_left.xml
  app/src/main/res/animator/slide_out_right.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_clone.xml
  app/src/main/res/layout/fragment_repo_location.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1107 Add @Keep annotation to WelcomeFragment class
  app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/WelcomeFragment.kt
Labels: bug

#1108 Misc cleanups to build and extension functions
  app/build.gradle.kts
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/GitSettings.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/CredentialFinder.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshKey.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/AndroidExtensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/FragmentExtensions.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: code

#1110 Finish activity in case of external directory
  app/src/main/java/com/zeapo/pwdstore/ui/onboarding/fragments/RepoLocationFragment.kt
Labels: bug

#1115 Resolve broken unauthenticated access flow
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
Labels: blocking-release, regression

#1116 Remove Autofill onboarding prompt and cleanup strings
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/res/layout/fragment_clone.xml
  app/src/main/res/layout/fragment_repo_location.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: code

#1117 Sync strings from Crowdin
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/nonFree/res/values-de/strings.xml
  app/src/nonFree/res/values-pt-rBR/strings.xml
  app/src/nonFree/res/values-ru/strings.xml
Labels: blocking-release

#1122 Unwrap root cause for InvalidRemoteException
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
Labels: backport, bug
