Repository android-password-store/Android-Password-Store, pull requests merged in 2020-03, with the labels that each got.

#649 Upgrade all dependencies to latest revisions
  app/build.gradle
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 📚 dependencies

#653 Add support for Oreo Autofill
  .github/CODEOWNERS
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillMatcher.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillScenario.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategy.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategyDsl.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FeatureAndTrustDetection.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Form.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/OreoAutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/PublicSuffixListCache.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillPublisherChangedActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/PasswordViewHolder.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/res/drawable/ic_autofill_new_password.xml
  app/src/main/res/drawable/ic_person_black_24dp.xml
  app/src/main/res/drawable/ic_search_black_24dp.xml
  app/src/main/res/drawable/ic_warning_red_24dp.xml
  app/src/main/res/layout/activity_oreo_autofill_filter.xml
  app/src/main/res/layout/activity_oreo_autofill_publisher_changed.xml
  app/src/main/res/layout/encrypt_layout.xml
  app/src/main/res/layout/oreo_autofill_dataset.xml
  app/src/main/res/layout/oreo_autofill_filter_row.xml
  app/src/main/res/layout/oreo_autofill_instructions.xml
  app/src/main/res/layout/password_row_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/oreo_autofill_service.xml
  app/src/main/res/xml/preference.xml
  build.gradle
  dependencies.gradle
  scripts/hash_browser_app.sh
Labels: :gift: feature, 🔨 code

#660 Make preferred directory structure for Autofill configurable
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillPreferences.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
  app/src/main/res/layout/encrypt_layout.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: :gift: feature

#666 Workaround: Prevent fill-in datasets from being shown on Android R
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Form.kt
Labels: 🐛 bug

#668 Fix deletion of individual password files
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Labels: 🐛 bug
