Repository android-password-store/Android-Password-Store, pull requests merged in 2020-08, with the labels that each got.

#997 Refactor uses of applicationContext and startActivityForResult
  app/src/main/java/com/zeapo/pwdstore/Application.kt
  app/src/main/java/com/zeapo/pwdstore/ClipboardService.kt
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordExportService.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
  app/src/main/java/com/zeapo/pwdstore/SelectFolderActivity.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillPreferences.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/PublicSuffixListCache.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/BasePgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/XkpwdDictionary.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/com/zeapo/pwdstore/ui/adapters/PasswordItemRecyclerAdapter.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
Labels: code, in progress

#1005 Prompt user to install OpenKeychain when missing
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/crypto/BasePgpActivity.kt
  app/src/main/res/values/strings.xml
Labels: blocking-release, bug, ready

#999 Replicate key selection flow for directory creation
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/res/layout/folder_dialog_fragment.xml
  app/src/main/res/values/strings.xml
Labels: feature, ready

#1007 Uprev Gradle and dependencies
  app/proguard-rules.pro
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#1009 Notify user when remote branch is up-to-date
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt
  app/src/main/res/values/strings.xml
Labels: bug

#1010 Improve clone operation semantics
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/operation/CloneOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
Labels: bug

#1016 Add symlink support to JGit
  app/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: bug

#1019 Restore workaround for preventing empty commits
  app/build.gradle.kts
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/ResetToRemoteOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/SyncOperation.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: bug

#1020 Reland symlink support
  app/build.gradle.kts
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: bug

#1021 build: update to Kotlin 1.4
  buildSrc/src/main/java/Dependencies.kt
Labels: dependencies

#1024 Also invert copy_on_decrypt preference value
  app/src/main/res/xml/preference.xml
Labels: bug

#1025 build: update openpgp-ktx to 2.1.0
  buildSrc/src/main/java/Dependencies.kt
Labels: dependencies

#1023 Allow adding digits and symbols in XkPasswd generator using mask-like values
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/CapsType.kt
  app/src/main/java/com/zeapo/pwdstore/pwgenxkpwd/PasswordBuilder.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/XkPasswordGeneratorDialogFragment.kt
  app/src/main/res/layout/fragment_xkpwgen.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: code

#995 Add SSHJ backend for OpenKeychain authentication
  app/src/main/java/com/zeapo/pwdstore/Application.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitCommandExecutor.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/SshApiSessionFactory.java
  app/src/main/java/com/zeapo/pwdstore/git/operation/CredentialFinder.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/OpenKeychainKeyProvider.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/OpenKeychainWrappedKeyAlgorithmFactory.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshjConfig.kt
  app/src/main/java/com/zeapo/pwdstore/git/sshj/SshjSessionFactory.kt
Labels: code, ready

#1031 Sort by recently used
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1033 Fix incorrect preference key
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Labels: code, ready, regression

#1036 Wrap password creation layout in ScrollView
  CHANGELOG.md
  app/src/main/res/layout/password_creation_activity.xml
Labels: bug

#1047 Prevent racing double commits on password creation
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
Labels: backport, regression

#1049 Return HTTPS URI username from CredentialsProvider
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
Labels: backport, bug

#1053 Rename ConnectionMode to AuthMode and remove clone_ prefix
  app/src/androidTest/java/com/zeapo/pwdstore/MigrationsTest.kt
  app/src/main/java/com/zeapo/pwdstore/Migrations.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/GitSettings.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/CredentialFinder.kt
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
  app/src/main/res/layout/activity_git_clone.xml
Labels: code

#1059 Expand show hidden folders to also cover files
  CHANGELOG.md
  app/src/androidTest/java/com/zeapo/pwdstore/MigrationsTest.kt
  app/src/main/java/com/zeapo/pwdstore/Migrations.kt
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
  app/src/main/java/com/zeapo/pwdstore/ui/adapters/PasswordItemRecyclerAdapter.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordItem.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: code, ready

#1060 Delete HTTPS instead of SSH key password on error
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
Labels: backport, regression

#1062 Remember HTTPS password throughout a sync operation
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/operation/GitOperation.kt
Labels: backport, bug

#1061 Do not return stored password on first retry
  app/src/main/java/com/zeapo/pwdstore/git/operation/CredentialFinder.kt
Labels: bug

#1056 Add Activity to view the Git commit log
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/log/GitCommit.kt
  app/src/main/java/com/zeapo/pwdstore/git/log/GitLogActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/log/GitLogAdapter.kt
  app/src/main/java/com/zeapo/pwdstore/git/log/GitLogModel.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/res/layout/activity_git_config.xml
  app/src/main/res/layout/activity_git_log.xml
  app/src/main/res/layout/git_log_row_layout.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1069 Simplify decrypt intent creation
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
Labels: code
