Repository android-password-store/Android-Password-Store, pull requests merged in 2020-11, with the labels that each got.

#1181 Improve Autofill UI and enable inline presentations
  .idea/gradle.xml
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillResponseBuilder.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillViewUtils.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/OreoAutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
  app/src/main/res/layout/activity_oreo_autofill_filter.xml
  app/src/main/res/layout/oreo_autofill_dataset.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/oreo_autofill_service.xml
Labels: type: feature

#1182 Make autofill-parser API explicit and refactor
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillResponseBuilder.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/OreoAutofillService.kt
  autofill-parser/api/autofill-parser.api
  autofill-parser/build.gradle.kts
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/AutofillFormParser.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/AutofillHelper.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/AutofillScenario.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/AutofillStrategy.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/AutofillStrategyDsl.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FormField.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/PublicSuffixListCache.kt
  autofill-parser/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt
Labels: type: refactor

#1185 Update openpgp-ktx and versions plugin
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: area: dependencies

#1192 Fix extra content for multiple username fields
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt
  app/src/test/java/com/zeapo/pwdstore/model/PasswordEntryTest.kt
Labels: A-passfile, C-bug

#1203 Update runtime dependencies to latest revisions
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: A-dependencies, P-low

#1207 Fix Autofill dataset icon tint
  CHANGELOG.md
  app/src/main/res/layout/oreo_autofill_dataset.xml
Labels: A-autofill, C-bug, E-easy, P-low, S-waiting-on-review

#1208 Refactor build setup for Gradle configuration cache support
  app/build.gradle.kts
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/PasswordStorePlugin.kt
  buildSrc/src/main/java/SigningConfig.kt
Labels: C-technical-debt, P-medium

#1212 Update Gradle and Kotlin
  buildSrc/build.gradle.kts
  buildSrc/buildDependencies.gradle
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: A-dependencies, E-medium

#1213 App shortcut fixes
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/res/drawable/ic_lock_open_24px.xml
Labels: C-bug, P-low

#1216 Automatically dismiss decryption screen after 60 seconds
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
Labels: C-bug, P-high
