Repository android-password-store/Android-Password-Store, pull requests merged in 2020-05, with the labels that each got.

#757 Confirm password move if it will replace an existing one
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Labels: 🐛 bug

#756 Better handle non-git repositories
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/res/menu/main_menu_git.xml
  app/src/main/res/menu/main_menu_non_git.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: :construction_worker_man: in progress, :scroll: documentation, 🐛 bug, 🔨 code

#764 PasswordEntry: add more potential fields for username
  app/src/androidTest/java/com/zeapo/pwdstore/PasswordEntryTest.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
Labels: 🐛 bug

#766 PasswordEntry: add user to the potential candidates for username
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
Labels: 🐛 bug

#772 Add setting for fallback username
  app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: :gift: feature

#762 Make APS buildable on F-Droid
  .github/workflows/update_publicsuffix_data.yml
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/assets/publicsuffixes
  app/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt
  app/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListData.kt
  app/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListLoader.kt
  app/src/main/java/mozilla/components/lib/publicsuffixlist/ext/ByteArray.kt
  build.gradle
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 🔨 code

#796 Introduce better R8 optimizations
  CHANGELOG.md
  app/build.gradle
  app/proguard-android-optimize.txt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
  app/src/main/res/layout/fragment_to_clone_or_not.xml
Labels: 🔨 code

#797 Introduce and switch to FragmentViewBindingDelegate
  app/build.gradle
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillPublisherChangedActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/FragmentViewBindingDelegate.kt
  dependencies.gradle
Labels: 🔨 code

#799 Resolve ViewBinding regressions
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/SelectFolderFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
Labels: :black_circle: regression, 🐛 bug

#802 treewide: update fragments to use LayoutRes constructor
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/SelectFolderFragment.kt
  app/src/main/java/com/zeapo/pwdstore/ToCloneOrNot.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
Labels: :black_circle: regression, 🐛 bug

#806 Remove HOTP/TOTP support
  CHANGELOG.md
  app/build.gradle
  app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Otp.java
  app/src/main/res/layout/decrypt_layout.xml
  app/src/main/res/layout/otp_confirm_layout.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
  app/src/test/java/com/zeapo/pwdstore/PasswordEntryTest.kt
Labels: 🔨 code

#815 Make commitChange honor finishWithResultOnEnd
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Labels: :black_circle: regression

#803 build: Upgrade all dependencies
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/java/com/zeapo/pwdstore/Application.kt
  build.gradle
  dependencies.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: :construction_worker_man: in progress, 📚 dependencies

#817 Completely revamp decrypted password screen
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
  app/src/main/res/layout/decrypt_layout.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🔨 code
