Repository android-password-store/Android-Password-Store, pull requests merged in 2020-07, with the labels that each got.

#905 Improve and refactor Autofill heuristics
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategy.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
Labels: code, ready

#907 Improve how secrets and stored and used
  release/encrypt-secret.sh
  release/keystore.cipher
  release/props.cipher
  release/signing-setup.sh
Labels: ready

#908 Run a treewide reformat
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/SshApiSessionFactory.java
  app/src/main/java/com/zeapo/pwdstore/utils/Otp.kt
  app/src/main/java/com/zeapo/pwdstore/utils/UriTotpFinder.kt
  app/src/main/res/drawable/ic_qr_code_scanner.xml
  app/src/main/res/layout/password_row_layout.xml
Labels: code, ready

#909 Scroll to files and enter folders when created
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
Labels: ready

#911 build: upgrade Gradle wrapper
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#900 Fill OTP fields with SMS codes
  .github/workflows/deploy_snapshot.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  CHANGELOG.md
  app/build.gradle
  app/src/free/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSmsActivity.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillHelper.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillScenario.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/Form.kt
  app/src/main/res/drawable/ic_autofill_sms.xml
  app/src/main/res/layout/activity_oreo_autofill_sms.xml
  app/src/main/res/values/strings.xml
  app/src/nonFree/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSmsActivity.kt
  dependencies.gradle
  release/deploy-snapshot.sh
Labels: feature

#914 Deploy both variants to snapshot directory
  .github/workflows/deploy_snapshot.yml
  app/build.gradle
  release/deploy-snapshot.sh
Labels: ready

#910 Migrate to ActivityResultContracts
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/SelectFolderActivity.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillFragment.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillPreferenceActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillRecyclerAdapter.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/AutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSaveActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/BreakOutOfDetached.kt
  app/src/main/java/com/zeapo/pwdstore/git/CloneOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitAsyncTask.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/PullOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/PushOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/ResetToRemoteOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/SshApiSessionFactory.java
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/ItemCreationBottomSheet.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/res/layout/activity_git_config.xml
  app/src/main/res/layout/decrypt_layout.xml
  app/src/main/res/layout/password_creation_activity.xml
  app/src/main/res/values-v23/bools.xml
  app/src/main/res/values/bools.xml
Labels: code, ready

#921 Work around Chrome Autofill issue
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ChromeCompatFix.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/values-v28/bools.xml
  app/src/main/res/values/bools.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/oreo_autofill_chrome_compat_fix.xml
  app/src/main/res/xml/preference.xml
Labels: bug

#923 styles: re-add alertDialogTheme override
  app/src/main/res/values/styles.xml
Labels: bug

#918 Move password export to the IO dispatcher
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/PasswordExportService.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/res/drawable/ic_round_import_export.xml
  app/src/main/res/values/strings.xml
Labels: bug

#927 Exclude third_party scope from reformats
  .idea/codeStyles/Project.xml
  .idea/scopes/third_party.xml
Labels: code, ready

#929 Properly guard against invalid renaming
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/res/layout/password_creation_activity.xml
  app/src/main/res/values/strings.xml
Labels: blocking-release, bug

#931 Add debug icon and update color palette
  app/src/debug/res/mipmap-hdpi/ic_launcher.webp
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/debug/res/mipmap-mdpi/ic_launcher.webp
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/debug/res/mipmap-xhdpi/ic_launcher.webp
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/debug/res/values/colors.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/preference.xml
Labels: discussion, ready

#934 github: update all Actions
  .github/workflows/deploy_snapshot.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .github/workflows/update_publicsuffix_data.yml
  .github/workflows/validate_wrapper.yml
Labels: dependencies

#916 Remove manual key selection and start actually using `.gpg-id`
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/BasePgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/DecryptActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/GetKeyIdsActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: code, feature, in progress

#938 Always allow SSH key generation
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
Labels: bug, discussion

#939 Remove type images
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/ui/adapters/PasswordItemRecyclerAdapter.kt
  app/src/main/res/drawable/ic_multiple_files_24dp.xml
  app/src/main/res/layout/password_row_layout.xml
Labels: discussion

#940 Improve UI when launching with biometric lock
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
Labels: discussion

#941 Fix Autofill result contract bug
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillDecryptActivity.kt
Labels: regression

#943 Add changelog entry for ed25519 support
  CHANGELOG.md
Labels: documentation

#944 Use a more common SSH version string
  app/src/main/java/com/zeapo/pwdstore/git/config/SshjConfig.kt
Labels: code

#953 build: upgrade all dependencies
  build.gradle
  dependencies.gradle
Labels: dependencies

#936 Migrate to Gradle Kotlin DSL
  .idea/gradle.xml
  app/build.gradle
  app/build.gradle.kts
  build.gradle
  build.gradle.kts
  buildSrc/.gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  dependencies.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: code, discussion, ready

#959 Fix a crash when parsing long key IDs
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
Labels: backport, regression

#958 Wire in fallback key selection flow
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/crypto/GetKeyIdsActivity.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/values/strings.xml
Labels: backport, bug, help wanted, in progress, regression

#961 Add CHANGELOG entries for 1.10.1
  CHANGELOG.md
Labels: documentation

#966 README: clarify build types
  README.md
Labels: documentation

#968 Expand OTP and PasswordEntry tests
  .github/workflows/pull_request.yml
  app/src/androidTest/java/com/zeapo/pwdstore/model/PasswordEntryAndroidTest.kt
  app/src/androidTest/java/com/zeapo/pwdstore/utils/UriTotpFinderTest.kt
Labels: code

#969 Properly handle files without passwords
  CHANGELOG.md
  app/src/androidTest/java/com/zeapo/pwdstore/model/PasswordEntryAndroidTest.kt
  app/src/main/java/com/zeapo/pwdstore/model/PasswordEntry.kt
  app/src/main/java/com/zeapo/pwdstore/utils/UriTotpFinder.kt
  app/src/test/java/com/zeapo/pwdstore/model/PasswordEntryTest.kt
Labels: backport, bug, ready

#972 Correctly set error on incorrect credentials
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
  app/src/main/res/layout/git_credential_layout.xml
Labels: bug

#982 Fix TOTP import button check semantics
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
Labels: bug

#977 Add ability to change default branch
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/BreakOutOfDetached.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/ResetToRemoteOperation.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PreferenceKeys.kt
  app/src/main/res/layout/activity_git_clone.xml
Labels: discussion, documentation, feature

#978 Upgrade to Kotlin 1.4
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillStrategyDsl.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FeatureAndTrustDetection.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/OreoAutofillService.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PasswordCreationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/SshjConfig.kt
  app/src/main/java/com/zeapo/pwdstore/pwgen/RandomPasswordGenerator.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: dependencies

#985 Fix two SMS Autofill crashes
  CHANGELOG.md
  app/src/nonFree/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillSmsActivity.kt
Labels: backport, bug

#990 Switch to non-deprecated stdlib methods
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/FormField.kt
Labels: code

#991 Downgrade coroutines to 1.3.6 to fix VerifyErrors
  CHANGELOG.md
  dependencies.gradle
Labels: backport, bug, ready, regression
