Repository android-password-store/Android-Password-Store, pull requests merged in 2020-04, with the labels that each got.

#683 Modernize file listing and search in AutofillFilterActivity
  app/build.gradle
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/AutofillPreferences.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/AutofillFilterActivity.kt
  app/src/main/java/com/zeapo/pwdstore/autofill/oreo/ui/PasswordViewHolder.kt
  app/src/main/res/layout/activity_oreo_autofill_filter.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: :construction_worker_man: in progress, :sos: help wanted

#693 Remove an erroneous check on directory moves
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
Labels: :black_circle: regression

#685 Refactor Git related activities
  CHANGELOG.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitOperationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitServerConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/ConnectionMode.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/Protocol.kt
  app/src/main/java/com/zeapo/pwdstore/git/config/SshApiSessionFactory.java
  app/src/main/java/com/zeapo/pwdstore/ui/dialogs/FolderCreationDialogFragment.kt
  app/src/main/java/com/zeapo/pwdstore/utils/Extensions.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  app/src/main/res/color/toggle_button_selector.xml
  app/src/main/res/drawable/bottom_line.xml
  app/src/main/res/drawable/red_rectangle.xml
  app/src/main/res/layout/activity_git_clone.xml
  app/src/main/res/layout/activity_git_config.xml
  app/src/main/res/layout/autofill_instructions.xml
  app/src/main/res/layout/git_passphrase_layout.xml
  app/src/main/res/layout/password_recycler_view.xml
  app/src/main/res/menu/git_clone.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  dependencies.gradle
Labels: 🔨 code

#721 Work around incompatibility between AndroidFastScroll and recyclerview-selection
  app/src/main/java/androidx/recyclerview/widget/FixOnItemTouchDispatchRecyclerView.java
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/res/layout/password_recycler_view.xml
  spotless.gradle
Labels: :heavy_check_mark: ready, 🔨 code

#723 Validate hostname protocol before saving
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
Labels: :skull_and_crossbones: blocking-release, 🐛 bug

#728 BaseGitActivity: don't remove saved password unnecessarily
  app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt
Labels: :heavy_check_mark: ready, 🐛 bug, 🔨 code

#734 Fix crash when using type independent sort
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
Labels: 🐛 bug

#732 Improve permission handling logic
  app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🐛 bug

#738 Better detect uninitialized repositories and offer to clone
  app/src/main/java/com/zeapo/pwdstore/PasswordFragment.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitOperationActivity.kt
  app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
  app/src/main/res/values/strings.xml
Labels: 🐛 bug

#741 auth: redo implementation with a cleaner and simpler API surface
  app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/utils/BiometricAuthenticator.kt
  app/src/main/java/com/zeapo/pwdstore/utils/auth/AuthenticationResult.kt
  app/src/main/java/com/zeapo/pwdstore/utils/auth/Authenticator.kt
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: :heavy_check_mark: ready, 🔨 code

#743 Fix search if external root dir starts with a dot
  app/src/main/java/com/zeapo/pwdstore/SearchableRepositoryViewModel.kt
Labels: 🐛 bug

#744 Improve UX around settings items
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt
  app/src/main/java/com/zeapo/pwdstore/git/GitConfigActivity.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeyGenFragment.kt
  app/src/main/java/com/zeapo/pwdstore/sshkeygen/SshKeygenTask.kt
  app/src/main/res/layout/activity_git_config.xml
  app/src/main/res/layout/fragment_ssh_keygen.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: :heavy_check_mark: ready, 🔨 code

#745 Add toggle for debug logging
  CHANGELOG.md
  app/src/main/java/com/zeapo/pwdstore/Application.kt
  app/src/main/java/com/zeapo/pwdstore/UserPreference.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
Labels: :gift: feature
