Repository android-password-store/Android-Password-Store, pull requests merged in 2021-12, with the labels that each got.

#1565 Cleanup dependency declarations and upgrade to Kotlin 1.6.0
  app/src/test/java/dev/msfjarvis/aps/util/settings/MigrationsTest.kt
  app/src/test/java/dev/msfjarvis/aps/util/totp/UriTotpFinderTest.kt
  app/src/test/java/dev/msfjarvis/aps/util/viewmodel/StrictDomainRegexTest.kt
  autofill-parser/src/test/kotlin/mozilla/components/lib/publicsuffixlist/PublicSuffixListLoaderTest.kt
  buildSrc/build.gradle.kts
  crypto-pgpainless/src/test/kotlin/dev/msfjarvis/aps/crypto/PGPKeyManagerTest.kt
  dependency-sync/build.gradle.kts
  format-common/src/test/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntryTest.kt
  format-common/src/test/kotlin/dev/msfjarvis/aps/util/totp/OtpTest.kt
  gradle/libs.versions.toml
Labels: A-dependencies

#1570 Convert all GHA references to normal versions
  .github/workflows/dependency_sync.yml
  .github/workflows/deploy_github_releases.yml
  .github/workflows/deploy_library_releases.yml
  .github/workflows/deploy_snapshot.yml
  .github/workflows/draft_new_release.yml
  .github/workflows/pull_request.yml
  .github/workflows/sync_crowdin.yml
  .github/workflows/update_publicsuffix_data.yml
  .github/workflows/validate_gradle_wrapper.yml
Labels: C-technical-debt, A-CI-CD, A-dependencies

#1571 Reorder workflow steps to fix cache failure
  .github/workflows/dependency_sync.yml
  .github/workflows/deploy_github_releases.yml
  .github/workflows/deploy_library_releases.yml
  .github/workflows/deploy_snapshot.yml
  .github/workflows/draft_new_release.yml
Labels: C-technical-debt, A-CI-CD

#1579 Upgrade workflows to use Java 17
  .github/ci-gradle.properties
  .github/workflows/dependency_sync.yml
  .github/workflows/deploy_github_releases.yml
  .github/workflows/deploy_library_releases.yml
  .github/workflows/deploy_snapshot.yml
  .github/workflows/draft_new_release.yml
  .github/workflows/pull_request.yml
  .github/workflows/sync_crowdin.yml
  .github/workflows/update_publicsuffix_data.yml
  build-logic/kotlin-plugins/src/main/kotlin/com.github.android-password-store.kotlin-common.gradle.kts
Labels: C-technical-debt, A-CI-CD

#1580 Allow importing TOTP from images
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivityV2.kt
  app/src/main/res/values/strings.xml
Labels: P-medium, C-feature, A-UI-UX

#1582 Prevent Git files from turning up in search and listing
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/util/viewmodel/SearchableRepositoryViewModel.kt
Labels: C-technical-debt, P-low, A-pass-list

#1583 Refactor coroutine testing setup
  app/build.gradle.kts
  app/src/main/java/dev/msfjarvis/aps/injection/coroutines/DispatcherModule.kt
  app/src/main/java/dev/msfjarvis/aps/injection/totp/TotpModule.kt
  coroutine-utils-testing/api/coroutine-utils-testing.api
  coroutine-utils-testing/build.gradle.kts
  coroutine-utils-testing/src/main/kotlin/dev/msfjarvis/aps/test/CoroutineTestRule.kt
  coroutine-utils/api/coroutine-utils.api
  coroutine-utils/build.gradle.kts
  coroutine-utils/src/main/kotlin/dev/msfjarvis/aps/util/coroutines/DispatcherProvider.kt
  format-common/api/format-common.api
  format-common/build.gradle.kts
  format-common/src/main/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntry.kt
  format-common/src/test/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntryTest.kt
  settings.gradle.kts
Labels: C-technical-debt

#1587 Miscellaneous build and CI cleanups
  .github/workflows/pull_request.yml
  autofill-parser/build.gradle.kts
  build-logic/android-plugins/build.gradle.kts
  build-logic/android-plugins/src/main/kotlin/com.github.android-password-store.android-library.gradle.kts
  build-logic/android-plugins/src/main/kotlin/com.github.android-password-store.published-android-library.gradle.kts
  build-logic/kotlin-plugins/src/main/kotlin/com.github.android-password-store.kotlin-library.gradle.kts
  dependency-sync/build.gradle.kts
  gradle/libs.versions.toml
  openpgp-ktx/build.gradle.kts
  settings.gradle.kts
Labels: C-technical-debt, A-CI-CD

#1590 Batch dependency upgrades
  build-logic/kotlin-plugins/src/main/kotlin/com.github.android-password-store.kotlin-common.gradle.kts
  dependency-sync/build.gradle.kts
  gradle/libs.versions.toml
Labels: A-dependencies

#1596 gradle: turn off Configure-On-Demand
  gradle.properties
Labels: C-technical-debt, A-build

#1600 Upgrade to Gradle 7.3.3
  build-logic/android-plugins/build.gradle.kts
  build-logic/automation-plugins/build.gradle.kts
  build-logic/automation-plugins/src/main/kotlin/com.github.android-password-store.gradle.gradle.kts
  build-logic/kotlin-plugins/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: C-technical-debt, A-dependencies, A-build

#1601 Tweak PSL automerge to use GH CLI
  .github/workflows/update_publicsuffix_data.yml
Labels: C-technical-debt, A-CI-CD

#1602 Increase timeouts for Crowdin API build task
  build-logic/automation-plugins/src/main/kotlin/crowdin/CrowdinPlugin.kt
Labels: C-bug, A-CI-CD, A-localisation, A-build

#1611 Misc cleanups and fixes
  .github/workflows/update_publicsuffix_data.yml
  build-logic/android-plugins/build.gradle.kts
  build-logic/automation-plugins/build.gradle.kts
  build-logic/kotlin-plugins/build.gradle.kts
Labels: C-technical-debt, A-CI-CD, A-build

#1622 Misc cleanups to build-logic and expand BCV exclusion list
  build-logic/android-plugins/build.gradle.kts
  build-logic/android-plugins/src/main/kotlin/com.github.android-password-store.android-application.gradle.kts
  build-logic/android-plugins/src/main/kotlin/com.github.android-password-store.published-android-library.gradle.kts
  build-logic/automation-plugins/build.gradle.kts
  build-logic/kotlin-plugins/build.gradle.kts
  build-logic/kotlin-plugins/src/main/kotlin/com.github.android-password-store.binary-compatibility.gradle.kts
  build-logic/kotlin-plugins/src/main/kotlin/com.github.android-password-store.kotlin-kapt.gradle.kts
  coroutine-utils-testing/api/coroutine-utils-testing.api
  coroutine-utils/api/coroutine-utils.api
  crypto-common/api/crypto-common.api
  crypto-pgpainless/api/crypto-pgpainless.api
  format-common/api/format-common.api
  passgen/diceware/api/diceware.api
Labels: C-technical-debt, A-build

#1629 Recognize mail as alternative to email
  format-common/src/main/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntry.kt
  format-common/src/test/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntryTest.kt
Labels: C-feature, A-passfile

#1627 Refactor BiometricAuthenticator and add proper support for retries
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/main/LaunchActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/GeneralSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/dev/msfjarvis/aps/util/auth/BiometricAuthenticator.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/GitOperation.kt
Labels: C-bug, C-technical-debt, E-medium, P-medium, A-UI-UX

#1632 Restore Bromite support in autofill-parser
  CHANGELOG.md
  app/src/main/res/xml/oreo_autofill_service.xml
  autofill-parser/CHANGELOG.md
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt
Labels: A-autofill, C-feature

#1634 Release new version of autofill-parser
  autofill-parser/CHANGELOG.md
  autofill-parser/gradle.properties
Labels: A-autofill
