Repository android-password-store/Android-Password-Store, pull requests merged in 2021-04, with the labels that each got.

#1358 Update all dependencies
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FormField.kt
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: A-dependencies

#1368 Actively discourage use of git protocol
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/git/config/GitServerConfigActivity.kt
  app/src/main/res/values/strings.xml
Labels: A-Git, C-technical-debt, P-low, S-waiting-on-review

#1370 Mark non-native Autofill browsers as unsupported on Oreo
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt
Labels: A-UI-UX, A-autofill

#1372 Switch to sublime text's fuzzy matching
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/java/dev/msfjarvis/aps/util/viewmodel/SearchableRepositoryViewModel.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: A-UI-UX, C-technical-debt, P-medium, S-waiting-on-review

#1373 Add a changelog for autofill-parser
  autofill-parser/CHANGELOG.md
Labels: A-distribution, A-meta, C-doc, P-low

#1374 Refactor biometric preference handling
  app/src/main/java/dev/msfjarvis/aps/ui/settings/GeneralSettings.kt
Labels: A-UI-UX, C-bug, P-high

#1375 Declare and check for camera features
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
Labels: A-UI-UX, A-distribution, C-technical-debt, P-low

#1376 Update build dependencies
  .github/workflows/deploy_github_releases.yml
  buildSrc/src/main/java/Dependencies.kt
Labels: A-CI-CD, A-dependencies, P-medium

#1379 Sync localisations from Crowdin
  app/src/main/res/values-fr/strings.xml
Labels: A-localisation, P-low

#1381 Update to Gradle 7.0
  app/build.gradle.kts
  autofill-parser/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/Dependencies.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  openpgp-ktx/build.gradle.kts
  settings.gradle.kts
Labels: A-CI-CD, A-dependencies, C-technical-debt, P-medium

#1383 Fix library deployment workflow
  .github/workflows/deploy_library_releases.yml
  buildSrc/src/main/java/PasswordStorePlugin.kt
  buildSrc/src/main/java/SigningConfig.kt
Labels: A-CI-CD, A-distribution, C-bug, C-technical-debt, P-high

#1386 Remove hand-rolled CoroutineScope and fix inverted conditions
  app/src/main/java/dev/msfjarvis/aps/ui/autofill/AutofillDecryptActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/DecryptActivity.kt
Labels: A-UI-UX, A-passfile, C-bug, C-technical-debt, P-high

#1389 Migrate some tests to Robolectric
  app/build.gradle.kts
  app/src/test/java/dev/msfjarvis/aps/util/totp/UriTotpFinderTest.kt
  app/src/test/java/dev/msfjarvis/aps/util/viewmodel/StrictDomainRegexTest.kt
  gradle/libs.versions.toml
Labels: A-meta, C-technical-debt, P-medium, S-waiting-on-review

#1391 Enable StrictMode in debug logging builds
  app/src/main/java/dev/msfjarvis/aps/Application.kt
Labels: A-meta, C-technical-debt, P-medium

#1392 Refactor app shortcut handling
  app/src/main/java/dev/msfjarvis/aps/ui/passwords/PasswordStore.kt
  app/src/main/java/dev/msfjarvis/aps/util/shortcuts/ShortcutHandler.kt
Labels: A-meta, C-technical-debt, P-medium

#1394 Update AndroidX dependencies
  gradle/libs.versions.toml
Labels: A-dependencies

#1396 Do not ASCII armor files when encrypting
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
Labels: A-PGP, C-bug, P-low

#1397 Upgrade to Kotlin 1.5
  app/build.gradle.kts
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/DecryptActivity.kt
  app/src/main/java/dev/msfjarvis/aps/util/pwgen/RandomPhonemesGenerator.kt
  app/src/main/java/dev/msfjarvis/aps/util/pwgenxkpwd/PasswordBuilder.kt
  app/src/main/java/dev/msfjarvis/aps/util/viewmodel/SearchableRepositoryViewModel.kt
  autofill-parser/CHANGELOG.md
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FormField.kt
  autofill-parser/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListData.kt
  autofill-parser/src/main/java/mozilla/components/lib/publicsuffixlist/ext/ByteArray.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/BaseProjectConfig.kt
  format-common/src/main/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntry.kt
  format-common/src/main/kotlin/dev/msfjarvis/aps/util/totp/Otp.kt
  gradle/libs.versions.toml
  openpgp-ktx/CHANGELOG.md
  openpgp-ktx/src/main/java/me/msfjarvis/openpgpktx/util/OpenPgpUtils.kt
Labels: A-dependencies, C-technical-debt, P-low

#1398 Refactor openpgp-ktx to leverage coroutines
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/DecryptActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/GetKeyIdsActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
  autofill-parser/CHANGELOG.md
  openpgp-ktx/api/openpgp-ktx.api
  openpgp-ktx/gradle.properties
  openpgp-ktx/src/main/java/me/msfjarvis/openpgpktx/util/OpenPgpApi.kt
  openpgp-ktx/src/main/java/me/msfjarvis/openpgpktx/util/ParcelFileDescriptorUtil.kt
Labels: A-PGP, A-meta, C-technical-debt, P-medium, S-waiting-on-review
