Repository android-password-store/Android-Password-Store, pull requests merged in 2021-05, with the labels that each got.

#1402 Upgrade Kotlin and AndroidX dependencies
  build.gradle.kts
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: A-dependencies, C-technical-debt, P-low

#1407 Upgrade Gradle and `androidx.annotation`
  app/build.gradle.kts
  autofill-parser/build.gradle.kts
  buildSrc/src/main/java/BaseProjectConfig.kt
  format-common/build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: A-dependencies, C-technical-debt, P-medium

#1408 Bump Robolectric, Gradle and kotlinx.coroutines
  .github/workflows/draft_new_release.yml
  .github/workflows/sync_crowdin.yml
  .github/workflows/update_publicsuffix_data.yml
  buildSrc/src/main/java/BaseProjectConfig.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: A-CI-CD, A-dependencies

#1410 Offload some main thread disk reads to background thread
  app/src/main/java/dev/msfjarvis/aps/ui/adapters/PasswordItemRecyclerAdapter.kt
  app/src/main/java/dev/msfjarvis/aps/ui/autofill/AutofillFilterActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/folderselect/SelectFolderFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/passwords/PasswordFragment.kt
  app/src/main/java/dev/msfjarvis/aps/util/viewmodel/SearchableRepositoryViewModel.kt
Labels: A-pass-list, C-technical-debt, P-medium

#1419 Tweak git server config screen UI and remove unused resources
  app/src/main/res/layout/activity_git_clone.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hdpi/dimens.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: A-UI-UX, C-technical-debt, P-low

#1421 Add compose dependencies
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: A-UI-UX, A-dependencies, C-technical-debt, P-low

#1423 Remove Bromite from autofill supported browsers
  CHANGELOG.md
  app/src/main/res/xml/oreo_autofill_service.xml
  autofill-parser/CHANGELOG.md
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt
Labels: A-autofill, C-bug, P-high

#1426 Fix 'View generated SSH key' option showing when not applicable
  app/src/main/java/dev/msfjarvis/aps/ui/settings/RepositorySettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyGenActivity.kt
Labels: A-UI-UX, C-bug, P-low
