Repository android-password-store/Android-Password-Store, pull requests merged in 2021-08, with the labels that each got.

#1477 Upgrade Compose and other AndroidX libraries
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: A-dependencies, C-technical-debt, P-medium

#1480 Make password generator parameter changes reactive
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/java/dev/msfjarvis/aps/ui/dialogs/PasswordGeneratorDialogFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/dialogs/XkPasswordGeneratorDialogFragment.kt
  gradle/libs.versions.toml
Labels: P-medium, S-waiting-on-review, C-feature, A-UI-UX

#1481 Switch to our fork of the preference testing library
  gradle/libs.versions.toml
Labels: C-technical-debt, P-low, A-dependencies

#1483 Disable explicit API for tests
  autofill-parser/src/test/kotlin/mozilla/components/lib/publicsuffixlist/PublicSuffixListLoaderTest.kt
  buildSrc/src/main/java/PasswordStorePlugin.kt
  format-common/src/test/kotlin/dev/msfjarvis/aps/data/passfile/PasswordEntryTest.kt
  format-common/src/test/kotlin/dev/msfjarvis/aps/util/time/TestClocks.kt
  format-common/src/test/kotlin/dev/msfjarvis/aps/util/totp/OtpTest.kt
Labels: C-technical-debt

#1484 Upgrade ConstraintLayout, Material and Timber
  gradle/libs.versions.toml
Labels: A-dependencies

#1487 Add `KeyPair` and `KeyManager` to manage keys in the app
  .github/workflows/pull_request.yml
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/SlimTests.kt
  crypto-common/api/crypto-common.api
  crypto-common/build.gradle.kts
  crypto-common/src/main/kotlin/dev/msfjarvis/aps/data/crypto/CryptoException.kt
  crypto-common/src/main/kotlin/dev/msfjarvis/aps/data/crypto/KeyManager.kt
  crypto-common/src/main/kotlin/dev/msfjarvis/aps/data/crypto/KeyPair.kt
  crypto-pgp/api/crypto-pgp.api
  crypto-pgp/build.gradle.kts
  crypto-pgp/src/androidTest/kotlin/dev/msfjarvis/aps/crypto/GPGKeyManagerTest.kt
  crypto-pgp/src/androidTest/kotlin/dev/msfjarvis/aps/crypto/GPGKeyPairTest.kt
  crypto-pgp/src/androidTest/kotlin/dev/msfjarvis/aps/crypto/utils/CryptoConstants.kt
  crypto-pgp/src/androidTest/res/raw/private_key
  crypto-pgp/src/main/kotlin/dev/msfjarvis/aps/data/crypto/GPGKeyManager.kt
  crypto-pgp/src/main/kotlin/dev/msfjarvis/aps/data/crypto/GPGKeyPair.kt
  scripts/boot-emulator.sh
  scripts/setup-environment.sh
Labels: P-high, A-PGP, C-feature

#1488 Bump Gradle and Timber
  buildSrc/src/main/java/BaseProjectConfig.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: C-technical-debt, A-CI-CD, A-dependencies

#1491 Update AndroidX deps
  app/src/main/java/dev/msfjarvis/aps/ui/proxy/ProxySelectorActivity.kt
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/PublicSuffixListCache.kt
  autofill-parser/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixList.kt
  buildSrc/src/main/java/BaseProjectConfig.kt
  gradle/libs.versions.toml
Labels: A-dependencies

#1494 Directly push PSL updates to develop
  .github/workflows/update_publicsuffix_data.yml
Labels: C-technical-debt, P-medium, A-CI-CD
