Repository android-password-store/Android-Password-Store, pull requests merged in 2021-03, with the labels that each got.

#1335 Enable Kotlin's JVM IR backend
  buildSrc/src/main/java/BaseProjectConfig.kt
Labels: A-dependencies, P-low

#1338 Mark Chrome as reliably fillable and saveable
  CHANGELOG.md
  autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt
Labels: A-autofill

#1344 Append trailing newline to `.gpg-id` during creation
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/onboarding/fragments/KeySelectionFragment.kt
Labels: A-PGP, C-bug, P-high

#1347 Update Gradle and tighten repository inclusion rules
  build.gradle.kts
  buildSrc/src/main/java/BaseProjectConfig.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: A-CI-CD, C-technical-debt, P-medium, S-waiting-on-review

#1348 Migrate to sshauthentication-api's JitPack coordinates
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: A-dependencies, P-high

#1355 Inform users that GPG key selection is mandatory
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/onboarding/fragments/KeySelectionFragment.kt
  app/src/main/res/values/strings.xml
Labels: A-PGP, A-UI-UX, C-bug, P-medium

#1357 Do not cancel keygen biometric prompt on failure
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyGenActivity.kt
Labels: A-UI-UX, P-medium

#1359 Don't hardcode TOTP period
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/DecryptActivity.kt
Labels: A-UI-UX, C-bug, P-low
