Repository android-password-store/Android-Password-Store, pull requests merged in 2021-01, with the labels that each got.

#1266 Dependency updates
  buildSrc/buildDependencies.gradle
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: A-dependencies, P-low

#1267 Revert #1255
  app/src/main/java/dev/msfjarvis/aps/util/git/GitCommandExecutor.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/GitResult.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/GitOperation.kt
Labels: A-Git, C-bug, P-high, S-waiting-on-review

#1268 Show less obvious Autofill actions first
  app/src/main/java/dev/msfjarvis/aps/util/autofill/Api30AutofillResponseBuilder.kt
  app/src/main/java/dev/msfjarvis/aps/util/autofill/AutofillResponseBuilder.kt
Labels: A-UI-UX, A-autofill, P-low

#1270 Update Actions
  .github/workflows/deploy_github_releases.yml
  .github/workflows/draft_new_release.yml
  .github/workflows/pull_request.yml
  .github/workflows/update_publicsuffix_data.yml
  .github/workflows/weekly_crowdin_sync.yml
Labels: A-CI-CD, A-dependencies, P-medium

#1271 Fix auth modes not displaying properly
  app/src/main/res/layout/activity_git_clone.xml
  app/src/main/res/layout/fragment_clone.xml
  app/src/main/res/layout/fragment_key_selection.xml
  app/src/main/res/layout/fragment_repo_location.xml
  app/src/main/res/values-hdpi/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: A-UI-UX, C-bug, P-medium

#1275 Cleanup menu item handling
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/DecryptActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/folderselect/SelectFolderActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/git/config/GitConfigActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/git/config/GitServerConfigActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/passwords/PasswordStore.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/UserPreference.kt
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyGenActivity.kt
Labels: A-UI-UX, C-bug, P-medium, S-waiting-on-review

#1236 Rework settings to use ModernAndroidPreferences
  CHANGELOG.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/msfjarvis/aps/ui/onboarding/fragments/RepoLocationFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/onboarding/fragments/WelcomeFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/passwords/PasswordStore.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/AutofillSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/DirectorySelectionActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/GeneralSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/MiscSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/PasswordSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/RepositorySettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/SettingsActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/SettingsProvider.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/UserPreference.kt
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyImportActivity.kt
  app/src/main/java/dev/msfjarvis/aps/util/autofill/AutofillPreferences.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/GitOperation.kt
  app/src/main/res/drawable/app_settings_alt_24px.xml
  app/src/main/res/drawable/ic_call_merge_24px.xml
  app/src/main/res/drawable/ic_miscellaneous_services_24px.xml
  app/src/main/res/drawable/ic_wysiwyg_24px.xml
  app/src/main/res/layout/activity_preference_recyclerview.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-v29/arrays.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preference.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: A-UI-UX, C-feature, C-technical-debt, P-high, S-waiting-on-review

#1276 Allow configuring pull behaviour
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/git/base/BaseGitActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/git/config/GitConfigActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/RepositorySettings.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/ErrorMessages.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/GitCommandExecutor.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/BreakOutOfDetached.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/PullOperation.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/SyncOperation.kt
  app/src/main/java/dev/msfjarvis/aps/util/settings/GitSettings.kt
  app/src/main/java/dev/msfjarvis/aps/util/settings/PreferenceKeys.kt
  app/src/main/res/layout/activity_git_config.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: A-Git, C-feature, P-medium, S-waiting-on-author

#1279 Upgrade dependencies
  buildSrc/src/main/java/Dependencies.kt
Labels: A-dependencies, P-low

#1282 Migrate versioning to Gradle plugin and automate version bumps
  .github/workflows/draft_new_release.yml
  app/build.gradle.kts
  app/version.properties
  buildSrc/build.gradle.kts
  buildSrc/buildDependencies.gradle
  buildSrc/src/main/java/VersioningPlugin.kt
Labels: A-distribution, C-doc, C-feature, P-medium, S-waiting-on-review

#1283 Codestyle churn
  .editorconfig
  .idea/codeStyles/Project.xml
  app/src/main/java/dev/msfjarvis/aps/Application.kt
  app/src/main/java/dev/msfjarvis/aps/data/repo/PasswordRepository.kt
  app/src/main/java/dev/msfjarvis/aps/ui/autofill/AutofillDecryptActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/autofill/AutofillFilterActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/autofill/AutofillPublisherChangedActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/autofill/AutofillSaveActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/BasePgpActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/DecryptActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/dialogs/BasicBottomSheet.kt
  app/src/main/java/dev/msfjarvis/aps/ui/dialogs/FolderCreationDialogFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/dialogs/ItemCreationBottomSheet.kt
  app/src/main/java/dev/msfjarvis/aps/ui/dialogs/XkPasswordGeneratorDialogFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/folderselect/SelectFolderFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/git/base/BaseGitActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/git/config/GitConfigActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/git/config/GitServerConfigActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/main/LaunchActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/onboarding/fragments/CloneFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/onboarding/fragments/KeySelectionFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/onboarding/fragments/RepoLocationFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/passwords/PasswordFragment.kt
  app/src/main/java/dev/msfjarvis/aps/ui/passwords/PasswordStore.kt
  app/src/main/java/dev/msfjarvis/aps/ui/proxy/ProxySelectorActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/AutofillSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/DirectorySelectionActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/GeneralSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/MiscSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/PasswordSettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/RepositorySettings.kt
  app/src/main/java/dev/msfjarvis/aps/ui/settings/SettingsActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyGenActivity.kt
  app/src/main/java/dev/msfjarvis/aps/ui/sshkeygen/SshKeyImportActivity.kt
  app/src/main/java/dev/msfjarvis/aps/util/autofill/Api30AutofillResponseBuilder.kt
  app/src/main/java/dev/msfjarvis/aps/util/autofill/AutofillMatcher.kt
  app/src/main/java/dev/msfjarvis/aps/util/autofill/AutofillResponseBuilder.kt
  app/src/main/java/dev/msfjarvis/aps/util/autofill/AutofillViewUtils.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/GitCommandExecutor.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/CredentialFinder.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/operation/GitOperation.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/sshj/OpenKeychainKeyProvider.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/sshj/SshKey.kt
  app/src/main/java/dev/msfjarvis/aps/util/git/sshj/SshjSessionFactory.kt
  app/src/main/java/dev/msfjarvis/aps/util/pwgen/PasswordGenerator.kt
  app/src/main/java/dev/msfjarvis/aps/util/pwgenxkpwd/XkpwdDictionary.kt
  app/src/main/java/dev/msfjarvis/aps/util/services/ClipboardService.kt
  app/src/main/java/dev/msfjarvis/aps/util/services/OreoAutofillService.kt
  app/src/main/java/dev/msfjarvis/aps/util/settings/Migrations.kt
  app/src/main/java/dev/msfjarvis/aps/util/viewmodel/SearchableRepositoryViewModel.kt
  autofill-parser/src/main/java/mozilla/components/lib/publicsuffixlist/PublicSuffixListData.kt
  buildSrc/src/main/java/BaseProjectConfig.kt
Labels: C-technical-debt, P-high

#1286 Disallow overwriting passwords when editing
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/crypto/PasswordCreationActivity.kt
Labels: A-UI-UX, C-bug, P-high, S-waiting-on-review

#1289 Upgrade dependencies
  .github/workflows/pull_request.yml
  buildSrc/src/main/java/Dependencies.kt
Labels: A-dependencies, P-low

#1292 Fix app shortcuts not updating
  CHANGELOG.md
  app/src/main/java/dev/msfjarvis/aps/ui/passwords/PasswordStore.kt
Labels: A-UI-UX, C-bug, P-low, S-waiting-on-review
