Repository android-password-store/Android-Password-Store, pull requests merged in 2024-07, with the labels that each got.

#3107 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3115 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3120 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3128 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3127 add checkbox in passphrase dialog to clear cache
  app/src/main/java/app/passwordstore/ui/autofill/AutofillDecryptActivity.kt
  app/src/main/java/app/passwordstore/ui/crypto/DecryptActivity.kt
  app/src/main/java/app/passwordstore/ui/crypto/PasswordDialog.kt
  app/src/main/res/layout/dialog_password_entry.xml
  app/src/main/res/values/strings.xml
Labels: S-waiting-on-review, C-feature, A-PGPainless

#3136 Fix application crash when disabling cache auto-clear option and potential attack vector
  app/src/main/java/app/passwordstore/ui/settings/PGPSettings.kt
  app/src/main/res/values/strings.xml
Labels: C-bug, P-high, S-waiting-on-author, A-PGPainless

#3139 Sync localisations from Crowdin
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
Labels: A-localisation, S-automerge

#3142 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3144 fix null pointer exception when using public only keys (#3143)
  crypto/pgpainless/src/main/kotlin/app/passwordstore/crypto/PGPainlessCryptoHandler.kt
  crypto/pgpainless/src/test/kotlin/app/passwordstore/crypto/PGPainlessCryptoHandlerTest.kt
Labels: C-bug, P-high, S-waiting-on-author, A-PGPainless
