Repository android-password-store/Android-Password-Store, pull requests merged in 2024-08, with the labels that each got.

#3150 Sync localisations from Crowdin
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
Labels: A-localisation, S-automerge

#3151 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3162 fix blocking createPasswordUI() when OTP is displayed
  app/src/main/java/app/passwordstore/ui/crypto/DecryptActivity.kt
Labels: C-bug, P-high, A-UI-UX

#3161 add user ID input field (password creation/edit), may fix #1458
  app/src/main/java/app/passwordstore/data/password/FieldItem.kt
  app/src/main/java/app/passwordstore/ui/adapters/FieldItemAdapter.kt
  app/src/main/java/app/passwordstore/ui/crypto/DecryptActivity.kt
  app/src/main/java/app/passwordstore/ui/crypto/PasswordCreationActivity.kt
  app/src/main/res/layout/password_creation_activity.xml
  app/src/main/res/values/strings.xml
  format/common/src/main/kotlin/app/passwordstore/data/passfile/PasswordEntry.kt
Labels: P-medium, C-feature, A-UI-UX

#3163 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3177 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge

#3188 Update Public Suffix List data
  autofill-parser/src/main/assets/publicsuffixes
Labels: A-PSL, S-automerge
